### ISSUE TITLE
MessageHandler.transmit() trying to send messages while the connection is closed

### ISSUE THREAD

**Issue by Aivech** [DaMachinator/CivilEngineering#3]
There should be some check so that if the connection is closed (either because the receiving thread failed to connect or by the '/bridge disconnect' command), it will not try to transmit.

Additionally, if this function fails to send messages, it should close the receiving side as well (possibly configurable?).

**Comment by NikkyAI** [comment]
if the sender cannot send then the receiving side should have already crashed or returned.. from what i can tell

**Comment by NikkyAI** [comment]
fixed in GH-6
