### ISSUE TITLE
Command block user field is converted to {NOPINGNICK}

### ISSUE THREAD

**Issue by Aivech** [DaMachinator/CivilEngineering#5]
Relaying /say messages from the command block results in the single character `@` being submitted as the USER field of the ApiMessage created. Sending this through the relay results in this issue.

Possible fixes: Check for command blocks or that user == "@" and substitute a different username, perhaps CommandBlock?

**Comment by NikkyAI** [comment]
that is probably because the bridge is setup to stripNicks .. as in remove al lthat is not alphanumerical
if nothing is left over.. it behaves buggy and prints the format string itself.. since nothing was passed to it

**Comment by Aivech** [comment]
What should we use as the commandblock user instead of `@`? Just print `Server`?

**Comment by NikkyAI** [comment]
i think it should be configurable.. if we want commandblocks to be picked up by the bridge and then.. how does opencomputers chatboxes or whatever they are called get picked up ?

**Comment by Aivech** [comment]
As of right now it uses CommandBlock instead of @ as the username. I don't think OC chatboxes will get picked up unless they fire the server chat event or use CommandBroadcast.
